#!/usr/bin/env bash

printf "Content-type: application/json\n\n"

echo "[
  {
    \"columns\": [
      { \"text\": \"Time\", \"type\": \"time\", \"sort\": true, \"desc\": true },
      { \"text\": \"foo\" }
    ],
    \"rows\": [[$(( $(date +%s) * 1000 )),$RANDOM]],
    \"type\": \"table\"
  }
]
"

